#!/bin/bash

go run send.go First message.
go run send.go Second message..
go run send.go Third message...
go run send.go Fourth message....
go run send.go Fifth message.....
go run send.go Sixth message......
go run send.go Seventh message.......
go run send.go Eighth message........
go run send.go Ninth message.........
go run send.go Tenth message..........
